/datum/voicepack/abomination/get_sound(soundin, modifiers)
	var/used
	switch(soundin)
		if("aggro")
			used = pick('sound/vo/mobs/abomination/abomination_scream1.ogg','sound/vo/mobs/abomination/abomination_scream2.ogg')
		if("rage")
			used = pick('sound/vo/mobs/abomination/abomination_scream1.ogg','sound/vo/mobs/abomination/abomination_scream2.ogg')
		if("deathgurgle")
			used = pick('sound/vo/mobs/abomination/abom_death.ogg')
		if("firescream")
			used = pick('sound/vo/mobs/abomination/abom_death.ogg')
		if("painscream")
			used = pick('sound/vo/mobs/abomination/abom_pain1.ogg','sound/vo/mobs/abomination/abom_pain2.ogg','sound/vo/mobs/abomination/abom_pain3.ogg')
		if("agony")
			used = pick('sound/vo/mobs/abomination/abom_pain1.ogg','sound/vo/mobs/abomination/abom_pain2.ogg','sound/vo/mobs/abomination/abom_pain3.ogg')
		if("jump")
			used = pick('sound/vo/mobs/abomination/abom_jump.ogg')
		if("leap")
			used = pick('sound/vo/mobs/abomination/abom_jump.ogg')
		if("pain")
			used = pick('sound/vo/mobs/abomination/abom_pain1.ogg','sound/vo/mobs/abomination/abom_pain2.ogg','sound/vo/mobs/abomination/abom_pain3.ogg')
		if("paincrit")
			used = pick('sound/vo/mobs/abomination/abom_pain1.ogg','sound/vo/mobs/abomination/abom_pain2.ogg','sound/vo/mobs/abomination/abom_pain3.ogg')
		if("scream")
			used = pick('sound/vo/mobs/abomination/abomination_scream1.ogg','sound/vo/mobs/abomination/abomination_scream2.ogg')
		if("idle")
			used = pick('sound/vo/mobs/abomination/abom_speech1.ogg','sound/vo/mobs/abomination/abom_speech2.ogg','sound/vo/mobs/abomination/abom_speech3.ogg', 'sound/vo/mobs/abomination/abom_speech4.ogg', 'sound/vo/mobs/abomination/abom_speech5.ogg')


	return used
